### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by kimisme9386** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#13]
Error Message

```
1 validation error detected: Value '' at 'value' failed to satisfy constraint: Member must have length greater than or equal to 1. (Service: AWSSimpleSystemsManagement; Status Code: 400; Error Code: ValidationExcept
ion; Request ID: 35d8c36c-dbaa-4cff-a7cf-dcce65bd53e5)
```

CloudFormation Template

```yaml
Parameters:
  CommandRole:
    Type: String
    Description: 'https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#role'

  Command:
    Type: String
    Description: 'https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#command'

  KeyId:
    Type: String
    Description: 'https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#keyid'

Resources:
  Command:
    Type: 'AWSUtility::CloudFormation::CommandRunner'
    Properties:
      Command: !Ref Command
      Role: !Ref CommandRole
      KeyId: !Ref KeyId
```
