### ISSUE TITLE
Cfn stack create keeps failing with error 'Value '' at 'value' failed to satisfy constraint'

### ISSUE THREAD

**Issue by Shukla-Ankur** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#19]
I am trying to find the latest snapshot identifier for a RDS instances. I use this output to restore a DB instance from the snapshot identifier.
I have given RDSFullReadAccess to the commandrunner role 

 cfn template :
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "cfn"
Description: "test"

Resources:
  LatestSnapshotIdentifier:
    Type: AWSUtility::CloudFormation::CommandRunner
    Properties:
      Command: 'aws rds describe-db-snapshots --region ap-south-1 --db-instance-identifier ap-s1-test-rds-pg-sg-0 --query "DBSnapshots[0].DBInstanceIdentifier" --output text > /command-output.txt'
```

Expected output:
commandrunner should successfully execute this command

actual output:
getting an error
```

1 validation error detected: Value '' at 'value' failed to satisfy constraint: Member must have length greater than or equal to 1. (Service: AWSSimpleSystemsManagement; Status Code: 400; Error Code: ValidationException; Request ID: 341ac0af-5b67-46fd-9cdd-d99504a9e7eb)
--
```

I tried a bunch of things- in order to see if this is permissions issue, 
1. modified template to run this command - 

```
aws s3 mb s3://test-storage-as-0 --region ap-south-1 > /command-output.txt
```
failed

2. ```
 aws s3 ls |tail -n 1 > command-output.txt
```
Failed

3. 
4. ```
aws ec2 describe-instances --instance-ids i-042f829ed0c341724 --region ap-south-1 --profile dev --query="Reservations[0]|Instances[0]|InstanceId
```

Failed 

The overall experience was that cfn failed to work with any aws cli command in general.
