### ISSUE TITLE
Can't get it working - validation error

### ISSUE THREAD

**Issue by r3m4k3** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#20]
Hi there, 
I'm trying to use command runner with CF.

Here's my CF file, it's pretty simple:

```
AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  CommandRunner:
    Type: AWSUtility::CloudFormation::CommandRunner
    Properties:
      Command: aws s3 ls
      Role: TestEC2Role
```

Then I get this error: 
`Resource handler returned message: "1 validation error detected: Value '' at 'value' failed to satisfy constraint: Member must have length greater than or equal to 1. (Service: AWSSimpleSystemsManagement; Status Code: 400; Error Code: ValidationException; `

My EC2 role is configured properly and I have installed commandrunner as it's described in docs.
Do you have any idea why it doesn't work?

Thank you! :)
