### ISSUE TITLE
Using Change Sets Causes "Internal Failure"

### ISSUE THREAD

**Issue by cyounkins** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#58]
To reproduce:
```
Resources:
  CommandRunner:
    Type: 'AWSUtility::CloudFormation::CommandRunner'
    Properties:
      Command: echo 1 > /command-output.txt
```
1. Create stack with template above
2. Modify to "echo 2", create change set
3. Execute change set
4. Observe the CommandRunner resource fails with "Internal Failure"

**Comment by Giaco9NN** [comment]
The same thing is happening to me. I'm using the SAM CLI and the utility to read an SSM parameter in another region created by a StackSet. This is particularly useful when creating an ACM certificate in North Virgina is required, and the same template needs the certificate ARN.

```
  rCertificateArn:
    DependsOn:
      - rACMCertificate
    Type: AWSUtility::CloudFormation::CommandRunner
    Properties:
      Command: aws ssm get-parameter --name /thepost/infrastructure/acm/certificate/arn --output text --region us-east-1 --query Parameter.Value > /command-output.txt
      Role: !Ref rCliReaderInstanceProfile
```
I had to change the logical id, so that CloudFormation create the resource from scratch
