### ISSUE TITLE
Get outputs from other resource

### ISSUE THREAD

**Issue by Bharath509** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#60]
I'm creating msk using cloud formation template, SInce msk resource in cloud formation only gives msk arn as output,
I ran an was command to get the bootstrap broker URL, But when running the command I'm not able to refer output from the msk resource **(!GetAtt MskCluster.Arn)**

Please help me fix this

**Comment by Manideepakakula** [comment]
Yeah, This is a primary use case that needs to be provided, deeply disappointed if there is no way to achieve this scenario

**Comment by shantgup** [comment]
You can do this, using the below format. `Fn::Sub` lets us specify the `GetAtt` like `${MskCluster.Arn}`, where `MskCluster` is the Logical ID of the resource. For more information on this, see [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#w9aac34c28c69b7).

```
Resources:
   CommandRunner:
      Type: AWSUtility::CloudFormation::CommandRunner
      Properties:
         Command:
            Fn::Sub: |
                echo ${MskCluster.Arn} > /command-output.txt
         LogGroup: my-cloudwatch-log-group
         Role: MyEC2InstanceProfile
```
