### ISSUE TITLE
Incorrect logical resource name in some README examples

### ISSUE THREAD

**Issue by pbrisbin** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#61]
The README shows the following differences among its code blocks:

First form (2 occurrences):

```yaml
Resources:
  CommandRunner: # <-- NOTE
    # ...

Outputs:
  Output:
    Value: !GetAtt "Command.Output"
```

Second form (4 occurrences):

```yaml
Resources:
  Command:
    # ...

Outputs:
  Output:
    Value: !GetAtt "Command.Output"
```

I'm 99% sure that for `!GetAtt "Command.Output"` to work, the resource must be logically named `Command` (second form), not `CommandRunner` (first form). But there's a lot of magic here, so I may be missing something.

Which is correct?
